name: Best Practice
slogan: Code, Software, Snippets, Tipps, Tricks, ...
markdown: kramdown
highlight: pygments
paginate: 15
paginate_path: /page:num
language: de
encoding: UTF-8
#timezone: Europe/Berlin
url: http://cniweb.github.io
baseurl: /best-practice
github_url: https://github.com/cniweb
comments:
  provider: disqus
  disqus:
    short_name: best-practice
github:
  username: cniweb
pages_list:
  Home: /best-practice
  Categories: /best-practice/categories
  Archive: /best-practice/archive
  Tags: /best-practice/tags
  About: /best-practice/about
  Sidemap: /best-practice/sitemap.xml
  Feed: /best-practice/atom.xml
defaults:
  -
    scope:
      path: "" # ein leerer string an dieser Stelle bezieht alle Projektateien ein
      type: posts
    values:
      layout: post
      comments: true
      author: Christian Häussler
      authors:
       - surname: Christian
         given-names: Häussler
         orcid: http://cniweb.github.io
         email: c-n-i@web.de
