name: Best Practice
markdown: kramdown
highlight: pygments
permalink: /:title/
paginate: 15
paginate_path: /page:num
language: "de"
encoding: "UTF-8"
timezone: "Europe/Berlin"
github:
  username: "cniweb/best-practice"
defaults:
  -
    scope:
      path: "" # ein leerer string an dieser Stelle bezieht alle Projektateien ein
      type: "posts"
    values:
      layout: "default"
      comments: true
