name: Best Practice
slogan: Code, Software, Snippets, Tipps, Tricks, ...
markdown: kramdown
highlight: pygments
paginate: 15
paginate_path: /page:num
language: de
encoding: UTF-8
timezone: Europe/Berlin
url: http://cniweb.github.io
baseurl: /best-practice
github_url: https://github.com/cniweb
comments:
  provider: disqus
  disqus:
    short_name: jekyllbootstrap
github:
  username: cniweb
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
defaults:
  -
    scope:
      path: "" # ein leerer string an dieser Stelle bezieht alle Projektateien ein
      type: posts
    values:
      layout: post
      author: Christian Häussler
      comments: true
